### ISSUE TITLE
Name: Trojan-Downloader.Win32.Bitser.dcv

### ISSUE THREAD

**Issue by xEzitx** [BullyWiiPlaza/JMaster-Duel-Bot#2]
Name: Trojan-Downloader.Win32.Bitser.dcv

**Comment by BullyWiiPlaza** [comment]
Wikipedia says:
> In computing, a Trojan horse is any malware that misleads users of its true intent.

The EXE is a launcher/updater for the JMaster Duel Bot. Anti Virus vendors cannot know if it's malicious or not so they think it's a trojan but they don't understand the purpose of the application and that it does exactly and only what it should do.

Also, it's normal for those types of tools to eventually get flagged. See my YouTube videos, the comments and the Discord server for proof that it's legit. You can also run it in a virtual machine to confirm. I cannot "fix" the false anti virus detections so I'm closing this ticket since it has sufficiently been explained. 👍

**Comment by noboi4** [comment]
> Name: Trojan-Downloader.Win32.Bitser.dcv

its not a trojan, any app that runs as administrator and isn't from a large company, or has the ability to install software/updates and isn't from a "trusted source" will be flagged (falsely most of the time) as a trojan.

**Comment by BullyWiiPlaza** [comment]
For future reference, please kindly check the attached virustotal scan on the releases tab on GitHub which says the app is only detected by 1 out of 70 antivirus engines or something like that: https://github.com/BullyWiiPlaza/JMaster-Duel-Bot/releases
Obviously that's very, very safe.
