### ISSUE TITLE
环境检测问什么有问题

### ISSUE THREAD

**Issue by 1622208530** [BullyWiiPlaza/JMaster-Duel-Bot#20]
我使用的window10（64位
![54FDF73D832DA0FF32DB92ED471398AA](https://user-images.githubusercontent.com/132566755/236181082-7693f7d4-cccf-465f-b683-89625acca57e.jpg)
）java19.0.2环境都设置好了为什么启用检测仍然有问题

**Comment by RiceFl0wer** [comment]
不如你自己百度一下怎么配置JAVA环境

**Comment by 1622208530** [comment]
> 不如你自己百度一下怎么配置JAVA环境

我再去试试，我之前按百度的来的呀

**Comment by BullyWiiPlaza** [comment]
你好，通常应该有一个有用的错误信息，但它是空的。

请检查你的`PATH`环境变量是否包含`java.exe`，以及它是否工作正常。

另外，你可以尝试发送`Launcher.log`文件，让我看一下。

---

Hello, normally there should be a useful error message but it's empty.

Please check your `PATH` environment variable if it contains a `java.exe` and if it's working fine or not.

Also, you can try sending the `Launcher.log` file so that I can take a look.
