### ISSUE TITLE
Sorry but the server doesnt seem to be reachable.

### ISSUE THREAD

**Issue by noboi4** [BullyWiiPlaza/JMaster-Duel-Bot#24]
i have used this program in the past, but i re-downloaded it and got the following error:

"Sorry but the server doesnt seem to be reachable. make sure to check your internet or VPN and try again. also, make sure that your antivirus does not block the connection. contact the developer if the issue persists."

I have checked all the normal things and the things outlined in the error message, but it doesnt has not fixed it.

is this tool dead?

**Comment by BullyWiiPlaza** [comment]
No, the tool is not dead. The issue is on your end. Please verify:

1) Your Firewall is not blocking the connection
2) Your Antivirus (especially Malwarebytes) is not blocking the connection or detecting anything as a virus
3) You installed all Windows Updates
4) You rebooted your PC
5) You use no VPN or a VPN to a country which is allowed to access my website https://bullywiiplaza.website

**Comment by noboi4** [comment]
hello, it was my non-vpn connection. once connecting to a vpn (same country) it worked fine. thank you!
