### ISSUE TITLE
Duel Bot Not taking Negate into account Burn Nurse

### ISSUE THREAD

**Issue by marder1991** [BullyWiiPlaza/JMaster-Duel-Bot#9]
So, IDK if it is a bug or just an oversight the burn nurse duel bot will still attempt to activate Healing traps even if Darkworld Nurse or bad reaction to simochi have their effects negated but still on the field, if it's a bug I assume you will fix it when you get the chance, if it's an oversight can you add a check for cards being negated, I know your using screen shots to run bot negated cards have a circle with a cross through them, if you could get the burn nurse bot to check for this it would be awesome thanks

**Comment by marder1991** [comment]
While I'm thinking about it a feature for users to add their own fork conditions, as well as build their own duel bots using fork conditions and card priority would be awesome.

**Comment by BullyWiiPlaza** [comment]
Hi, it wasn't implemented because I currently have no good way to check for negated cards and using image searching is not very reliable and if you get one of the reverse healing cards negated you mostly lost anyway so that wasn't important enough to work on.

About custom duel bots, this was requested a few times but would you be interested in writing a script for it or do you just hope someone else will and then nobody feels responsible. I won't make and release this type of feature if people aren't willing to put some effort into it.

**Comment by marder1991** [comment]
you make a fire point, could you implement YGO pro's duel ai, and sorry if I am mistaken I thought you where using image searching, for the bot to begin with because of the log, again sorry was not trying to be annoying just thought I would bring it up thanks for the info.

**Comment by marder1991** [comment]
Lastly your work is awesome, and thanks for the bot.

**Comment by BullyWiiPlaza** [comment]
> you make a fire point, could you implement YGO pro's duel ai, and sorry if I am mistaken I thought you where using image searching, for the bot to begin with because of the log, again sorry was not trying to be annoying just thought I would bring it up thanks for the info.

I use image searching for the menu navigation but not during duels. However, YGOPro is not the same game engine as Konami's so you cannot simply implement YGOPro's AI either. Doing any of this is not as easy as it seems to be, I already thought about it extensively. I only came up with making a new one from scratch using Konami's API to get details about the duel and to supply duel commands (e.g. activate spell etc.)
